sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t travis-ci-build-stages-demo .
      - docker push travis-ci-build-stages-demo
    - stage: test
      script: docker run --rm travis-ci-build-stages-demo cat hello.txt
    - script: docker run --rm travis-ci-build-stages-demo cat hello.txt
