sudo: false

jobs:
  include:
    - stage: unit tests
      script: echo one
    - stage: unit tests
      script: echo two
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: web-sys-dev-heroku
        api_key: $HEROKU_AUTH_TOKEN
        on: web-sys-dev-heroku
    - stage: test staging
      script: 'curl https://web-sys-dev-heroku.herokuapp.com/'
    - stage: deploy to production
      script: /bin/true
      deploy:
        <<: *heroku
        app: web-sys-dev-heroku
    - stage: test production
      script: 'curl https://web-sys-dev-heroku.herokuapp.com/'

	  
	  
	  